# Generated by Django 5.0 on 2023-12-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durasi', models.IntegerField(default=1)),
                ('harga', models.IntegerField(default=50000)),
                ('diskon', models.IntegerField(default=40000)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=224, unique=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='photo/level')),
                ('keterangan', models.CharField(max_length=224)),
                ('nyawa', models.IntegerField(default=0)),
                ('biaya', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('promo', models.IntegerField(default=0)),
                ('bestseller', models.BooleanField(default=False)),
                ('pertemuan', models.IntegerField(default=0)),
                ('siswa', models.IntegerField(default=0)),
                ('durasi', models.IntegerField(default=1)),
                ('mengulang', models.BooleanField(default=False)),
                ('ketentuan', models.CharField(blank=True, max_length=225, null=True)),
                ('materi', models.CharField(blank=True, max_length=225, null=True)),
                ('bonus', models.CharField(blank=True, max_length=225, null=True)),
                ('langganan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langganan', to='kelas.langganan')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bahasa', models.CharField(blank=True, choices=[('EN', 'English'), ('JP', 'Japan'), ('SA', 'Arab'), ('CN', 'China')], default=1, max_length=3)),
                ('time', models.IntegerField(blank=True, choices=[(0, '07:30'), (1, '09:00'), (2, '10:30'), (3, '13:00'), (4, '14:30'), (5, '16:00'), (6, '18:30'), (7, '20:00')], default=1)),
                ('mulai', models.DateField(blank=True, null=True)),
                ('jadwal', models.IntegerField(blank=True, choices=[(0, "senin,  rabu, jum'at"), (1, 'selasa,  kamis, sabtu'), (2, "jum'at,  sabtu, minggu")], default=1)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_room', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun_room', to='kelas.program')),
            ],
        ),
        migrations.CreateModel(
            name='Schadule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terlaksana', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, choices=[(0, '07:30'), (1, '09:00'), (2, '10:30'), (3, '13:00'), (4, '14:30'), (5, '16:00'), (6, '18:30'), (7, '20:00')], default=1)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun_schadule', to='kelas.program')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_schadule', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schadule_room', to='kelas.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('meetremain', models.IntegerField(default=0)),
                ('accountlevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='kelas.program')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_meeting', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='kelas.kelas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMentored', models.BooleanField(default=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('like', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=224)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchadule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hadir', models.BooleanField(default=False)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_meeting', to='kelas.usermeeting')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_room', to='kelas.kelas')),
                ('schadule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_schadule', to='kelas.schadule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
