# Generated by Django 5.0 on 2023-12-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schadule',
            old_name='level',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='usermeeting',
            old_name='room',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='usermeeting',
            old_name='accountlevel',
            new_name='program',
        ),
        migrations.AddField(
            model_name='kelas',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_akun_room', to='kelas.program'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_akun_room', to='config.level'),
        ),
    ]
