# Generated by Django 5.0 on 2023-12-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_rename_level_schadule_program_and_more'),
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeeting',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaksi', to='transaksi.transaksi'),
        ),
    ]
