# Generated by Django 5.0 on 2023-12-25 10:11

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=224)),
                ('bahasa', models.CharField(blank=True, choices=[('EN', 'English'), ('JP', 'Japan'), ('SA', 'Arab'), ('CN', 'China')], max_length=3)),
                ('slug', models.SlugField(max_length=30, null=True)),
                ('photo', models.FileField(default='module/default.jpg', upload_to='module')),
                ('keterangan', models.CharField(blank=True, max_length=224)),
                ('rangkuman', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('defaultget', models.BooleanField(default=False)),
                ('biaya', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('premium', models.BooleanField(default=False)),
                ('mahkota', models.IntegerField(default=0)),
                ('dilihat', models.IntegerField(default=0)),
                ('certificate', models.BooleanField(default=False)),
                ('rilis', models.BooleanField(default=False)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori_module', to='config.kategori')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_module', to='config.level')),
            ],
        ),
        migrations.CreateModel(
            name='Bab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.CharField(max_length=50)),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('rangkuman', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_bab', to='modul.module')),
            ],
        ),
        migrations.CreateModel(
            name='Pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField(blank=True, null=True)),
                ('judul', models.CharField(max_length=224)),
                ('keterangan', models.CharField(default='belum ada keterangan', max_length=224)),
                ('vidio', models.URLField(blank=True, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('approve', models.BooleanField(default=False)),
                ('bab_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_module', to='modul.bab')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_pelajaran', to='modul.module')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('soal', models.CharField(max_length=224)),
                ('answer', models.CharField(max_length=224)),
                ('dummy', models.CharField(max_length=224)),
                ('penjelasan', models.TextField(default='Belum ada penjelasan')),
                ('approve', models.BooleanField(default=False)),
                ('bab_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_games', to='modul.bab')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Games_module', to='modul.module')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_pelajaran', to='modul.pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('finish', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('feed', models.CharField(blank=True, max_length=225, null=True)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
                ('enroll', models.BooleanField(default=False)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='modul.bab')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_course_user', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas', to='modul.module')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history_pelajaran', to='modul.pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.CharField(max_length=224)),
                ('answer', models.CharField(max_length=224)),
                ('wrong1', models.CharField(max_length=224)),
                ('wrong2', models.CharField(max_length=224)),
                ('wrong3', models.CharField(max_length=224)),
                ('penjelasan', models.TextField(default='Belum ada penjelasan')),
                ('approve', models.BooleanField(default=False)),
                ('bab_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bab_question', to='modul.bab')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_kategori', to='config.kategori')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_pelajaran', to='modul.pelajaran')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_level', to='config.level')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_module', to='modul.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perubahan', models.CharField(max_length=225)),
                ('approve', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_creator', to='modul.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdone', models.BooleanField(default=False)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_bab', to='modul.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_bab', to='modul.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bab_user', to=settings.AUTH_USER_MODEL)),
                ('userCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercourse_bab', to='modul.enroll')),
            ],
        ),
        migrations.CreateModel(
            name='UserGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_games', to='modul.bab')),
                ('games', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usergames_Games', to='modul.games')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usergames_kelas', to='modul.module')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_games_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_last', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('nilai', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('countdown', models.TimeField(default='00:10:00')),
                ('countdownNow', models.TimeField(default='00:10:00')),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan', to='modul.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_latihan', to='modul.module')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan_pelajaran', to='modul.pelajaran')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdone', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=225, null=True)),
                ('answer', models.CharField(blank=True, max_length=225, null=True)),
                ('tgl', models.DateField(blank=True, null=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bab_kelas_lesson', to='modul.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_kelas_lesson', to='modul.module')),
                ('pelajaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pelajaran', to='modul.pelajaran')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lesson_user', to=settings.AUTH_USER_MODEL)),
                ('userCourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercourse_lesson', to='modul.enroll')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.CharField(blank=True, max_length=225, null=True)),
                ('right', models.BooleanField(default=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('bab_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbab_Question', to='modul.bab')),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuestion_kelas', to='modul.module')),
                ('latihan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_latihan', to='modul.userlatihan')),
                ('questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuestion_Question', to='modul.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bahasa', models.CharField(blank=True, choices=[('EN', 'English'), ('JP', 'Japan'), ('SA', 'Arab'), ('CN', 'China')], max_length=3)),
                ('origin', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=50)),
                ('img', models.FileField(default='media/vocabgroup/default.jpg', upload_to='media/vocabgroup')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_group_level', to='config.level')),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('translate', models.CharField(max_length=50)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('vocabgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab_group', to='modul.vocabgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserVocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('benar', models.IntegerField(default=0)),
                ('salah', models.IntegerField(default=0)),
                ('isdone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_vocab_user', to=settings.AUTH_USER_MODEL)),
                ('vocab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to='modul.vocabgroup')),
            ],
        ),
    ]
