# Generated by Django 5.0 on 2023-12-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_start', models.DateField(blank=True, null=True)),
                ('premium_end', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='https://zoom.us/', max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(default=0)),
                ('api_key', models.CharField(max_length=50, null=True)),
                ('secret_key', models.CharField(max_length=50, null=True)),
                ('desc', models.CharField(max_length=225, null=True)),
                ('mastered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Master_of_teacher', to='config.master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=224)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo/profile')),
                ('join', models.DateField(auto_now_add=True)),
                ('kelas', models.IntegerField(default=1)),
                ('testi', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=224)),
                ('promo', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('nyawa', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('mahkota', models.IntegerField(default=0)),
                ('level', models.ForeignKey(default='Beginner', on_delete=django.db.models.deletion.CASCADE, related_name='progress_user', to='config.level', to_field='name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
