# Generated by Django 5.0 on 2023-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pendapatan',
            field=models.IntegerField(default=0),
        ),
    ]
