# Generated by Django 5.0 on 2023-12-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='purchased',
            new_name='terbayar',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='terpakai',
            field=models.BooleanField(default=False),
        ),
    ]
